// ALERT ACTION TYPES
export const ALERT_SUCCESS = 'ALERT_SUCCESS'
export const ALERT_ERROR = 'ALERT_ERROR'
export const ALERT_CLEAR = 'ALERT_CLEAR'

//GROUP ACTION TYPES
// Group Create Constants
export const CREATE_REQUEST = 'GROUPS_CREATE_REQUEST'
export const CREATE_SUCCESS = 'GROUPS_CREATE_SUCCESS'
export const CREATE_FAILURE = 'GROUPS_CREATE_FAILURE'
// Group Modify Constants
export const MODIFY_REQUEST = 'GROUPS_MODIFY_REQUEST'
export const MODIFY_SUCCESS = 'GROUPS_MODIFY_SUCCESS'
export const MODIFY_FAILURE = 'GROUPS_MODIFY_FAILURE'
// Group Get Constants
export const GETALL_REQUEST = 'GROUPS_GETALL_REQUEST'
export const GETALL_SUCCESS = 'GROUPS_GETALL_SUCCESS'
export const GETALL_FAILURE = 'GROUPS_GETALL_FAILURE'

// Group Delete Constants
export const DELETE_REQUEST = 'GROUPS_DELETE_REQUEST'
export const DELETE_SUCCESS = 'GROUPS_DELETE_SUCCESS'
export const DELETE_FAILURE = 'GROUPS_DELETE_FAILURE'

//TO-DO ACTION TYPES
// Todos Create Constants
export const TODOS_CREATE_REQUEST = 'TODOS_CREATE_REQUEST'
export const TODOS_CREATE_SUCCESS = 'TODOS_CREATE_SUCCESS'
export const TODOS_CREATE_FAILURE = 'TODOS_CREATE_FAILURE'

// Todos Modify Constants
export const TODOS_MODIFY_REQUEST = 'TODOS_MODIFY_REQUEST'
export const TODOS_MODIFY_SUCCESS = 'TODOS_MODIFY_SUCCESS'
export const TODOS_MODIFY_FAILURE = 'TODOS_MODIFY_FAILURE'

// Todos Get Constants
export const TODOS_GETALL_REQUEST = 'TODOS_GETALL_REQUEST'
export const TODOS_GETALL_SUCCESS = 'TODOS_GETALL_SUCCESS'
export const TODOS_GETALL_FAILURE = 'TODOS_GETALL_FAILURE'

// Todos Delete Constants
export const TODOS_DELETE_REQUEST = 'TODOS_DELETE_REQUEST'
export const TODOS_DELETE_SUCCESS = 'TODOS_DELETE_SUCCESS'
export const TODOS_DELETE_FAILURE = 'TODOS_DELETE_FAILURE'

//USERS ACTION TYPES
// User Registration Constants
export const USERS_REGISTER_REQUEST = 'USERS_REGISTER_REQUEST'
export const USERS_REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS'
export const USERS_REGISTER_FAILURE = 'USERS_REGISTER_FAILURE'

// User Create Constants
export const USERS_CREATE_REQUEST = 'USERS_CREATE_REQUEST'
export const USERS_CREATE_SUCCESS = 'USERS_CREATE_SUCCESS'
export const USERS_CREATE_FAILURE = 'USERS_CREATE_FAILURE'

// Users Modify Constants
export const USERS_MODIFY_REQUEST = 'USERS_MODIFY_REQUEST'
export const USERS_PROFILE_MODIFY_SUCCESS = 'USERS_PROFILE_MODIFY_SUCCESS'
export const USERS_MODIFY_SUCCESS = 'USERS_MODIFY_SUCCESS'
export const USERS_MODIFY_FAILURE = 'USERS_MODIFY_FAILURE'

// User Auth Constants
export const USERS_LOGIN_REQUEST = 'USERS_LOGIN_REQUEST'
export const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS'
export const USERS_LOGIN_FAILURE = 'USERS_LOGIN_FAILURE'
export const USERS_LOGOUT = 'USERS_LOGOUT'

// Users Get Constants
export const USERS_GETALL_REQUEST = 'USERS_GETALL_REQUEST'
export const USERS_GETALL_SUCCESS = 'USERS_GETALL_SUCCESS'
export const USERS_GETALL_FAILURE = 'USERS_GETALL_FAILURE'

// Users Delete Constants
export const USERS_DELETE_REQUEST = 'USERS_DELETE_REQUEST'
export const USERS_DELETE_SUCCESS = 'USERS_DELETE_SUCCESS'
export const USERS_DELETE_FAILURE = 'USERS_DELETE_FAILURE'

// Users Update Password Constants
export const USERS_PASSWORD_REQUEST = 'USERS_PASSWORD_REQUEST'
export const USERS_PASSWORD_SUCCESS = 'USERS_PASSWORD_SUCCESS'
export const USERS_PASSWORD_FAILURE = 'USERS_PASSWORD_FAILURE'

// API Key Generated Constants
export const USERS_GET_APIKEY_REQUEST = 'USERS_GET_APIKEY_REQUEST'
export const USERS_GET_APIKEY_SUCCESS = 'USERS_GET_APIKEY_SUCCESS'
export const USERS_GET_APIKEY_FAILURE = 'USERS_GET_APIKEY_FAILURE'